<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_board' => 'Board',
		'tt_board.subject' => 'Subject:',
		'tt_board.message' => 'Message:',
		'tt_board.parent' => 'Parent:',
		'tt_board.notify_me' => 'Notify by email:',
		'tt_board.crdate' => 'Date/Time:',
		'pi_list' => 'Board, List',
		'pi_tree' => 'Board, Tree',
	),
	'dk' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Emne:',
		'tt_board.message' => 'Indhold:',
		'tt_board.parent' => 'Forrige:',
		'tt_board.notify_me' => 'Orientering pr. email:',
		'tt_board.crdate' => 'Dato/Tidspunkt:',
		'pi_list' => 'Forum, Liste',
		'pi_tree' => 'Forum, Trж',
	),
	'de' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Titel:',
		'tt_board.message' => 'Mitteilung:',
		'tt_board.parent' => 'Vorherige:',
		'tt_board.notify_me' => 'Benachrichtigung per email:',
		'tt_board.crdate' => 'Datum/Zeit:',
		'pi_list' => 'Forum, Liste',
		'pi_tree' => 'Forum, Baum',
	),
	'no' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Emne:',
		'tt_board.message' => 'Innhold:',
		'tt_board.parent' => 'Forrige:',
		'tt_board.notify_me' => 'Orientering per Epost:',
		'tt_board.crdate' => 'Dato/tidspunkt:',
		'pi_list' => 'Forum, Liste',
		'pi_tree' => 'Forum, Tre',
	),
	'it' => Array (
		'tt_board' => 'Board',
		'tt_board.subject' => 'Soggetto:',
		'tt_board.message' => 'Messaggio:',
		'tt_board.parent' => 'Parent:',
		'tt_board.notify_me' => 'Notifica via email:',
		'tt_board.crdate' => 'Data/Ora:',
		'pi_list' => 'Forum, messaggi strutturati in una lista',
		'pi_tree' => 'Forum, messaggi strutturati ad albero',
	),
	'fr' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Sujet:',
		'tt_board.message' => 'Message:',
		'tt_board.parent' => 'Parent:',
		'tt_board.notify_me' => 'Avertir par e-mail:',
		'tt_board.crdate' => 'Date/Heure:',
		'pi_list' => 'Forum "message"',
		'pi_tree' => 'Forum "discution"',
	),
	'es' => Array (
		'tt_board' => 'Foro',
		'tt_board.subject' => 'Asunto:',
		'tt_board.message' => 'Mensaje:',
		'tt_board.parent' => 'Padre:',
		'tt_board.notify_me' => 'Notificar por email:',
		'tt_board.crdate' => 'Fecha/Hora:',
	),
	'nl' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Onderwerp:',
		'tt_board.message' => 'Bericht:',
		'tt_board.parent' => 'Bron:',
		'tt_board.notify_me' => 'Kennisgeving per email:',
		'tt_board.crdate' => 'Datum/Tijd:',
		'pi_list' => 'Forum, Lijst',
		'pi_tree' => 'Forum, Boom',
	),
	'cz' => Array (
		'tt_board' => 'Fуrum',
		'tt_board.subject' => 'Pшedmмt:',
		'tt_board.message' => 'Zprбva:',
		'tt_board.parent' => 'Odvozen:',
		'tt_board.notify_me' => 'Oznбmit e-mailem:',
		'tt_board.crdate' => 'Datum/Иas:',
		'pi_list' => 'Fуrum, seznamovй',
		'pi_tree' => 'Fуrum, stromovй',
	),
	'pl' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Temat:',
		'tt_board.message' => 'Wiadomo¶ж:',
		'tt_board.parent' => 'Nadrzкdny:',
		'tt_board.notify_me' => 'Powiadom emailem:',
		'tt_board.crdate' => 'Data/Czas:',
		'pi_list' => 'Forum, Lista',
		'pi_tree' => 'Forum, Drzewo',
	),
	'si' => Array (
		'tt_board' => 'Oglasna deska',
		'tt_board.subject' => 'Predmet:',
		'tt_board.message' => 'Sporoиilo:',
		'tt_board.notify_me' => 'Opozori po emailu:',
		'tt_board.crdate' => 'Datum/Ura:',
	),
	'fi' => Array (
		'tt_board' => 'Keskustelu',
		'tt_board.subject' => 'Asia:',
		'tt_board.message' => 'Viesti:',
		'tt_board.parent' => 'Edellinen:',
		'tt_board.notify_me' => 'Muistuta sдhkцpostitse:',
		'tt_board.crdate' => 'Pдivдys/Kello',
		'pi_list' => 'Ilmoitustaulu, lista',
		'pi_tree' => 'Ilmoitustaulu, puurakenne',
	),
	'tr' => Array (
		'tt_board' => 'Эlan tahtasэ',
		'tt_board.subject' => 'Konu:',
		'tt_board.message' => 'Mesaj:',
		'tt_board.parent' => 'Eю dьzey:',
		'tt_board.notify_me' => 'E-maille haber ver:',
		'tt_board.crdate' => 'Tarih/Zaman:',
		'pi_list' => 'Эlan tahtasi',
		'pi_tree' => 'Эlan tahtasэ, Aрaз',
	),
	'se' => Array (
	),
	'pt' => Array (
		'tt_board' => 'Quadro',
		'tt_board.subject' => 'Assunto:',
		'tt_board.message' => 'Mensagem:',
		'tt_board.parent' => 'Relativo a:',
		'tt_board.notify_me' => 'Notifique por email:',
		'tt_board.crdate' => 'Data/Hora:',
		'pi_list' => 'Quadro, Lista',
		'pi_tree' => 'Quadro, Бrvore',
	),
	'ru' => Array (
		'tt_board' => 'Форум',
		'tt_board.subject' => 'Тема:',
		'tt_board.message' => 'Сообщение:',
		'tt_board.parent' => 'Исходное:',
		'tt_board.notify_me' => 'Оповестить меня по адресу:',
		'tt_board.crdate' => 'Дата/время:',
		'pi_list' => 'Форум, список',
		'pi_tree' => 'Форум, дерево',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
);
?>