<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'title' => 'Plugins',
		'modules' => 'Available plugins',
		'shop_title' => 'Shop',
		'board_title' => 'Message Board',
		'fe_users_title' => 'Website users administration',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Newsletters',
		'news_title' => 'News',
		'approve_title' => 'Approvals',
	),
	'dk' => Array (
		'title' => 'Plugins',
		'modules' => 'Tilgængelige plugins',
		'shop_title' => 'Butik',
		'board_title' => 'Forum',
		'fe_users_title' => 'Website-bruger administration',
		'dmail_title' => 'Direct mail',
		'dmail_newsletters' => 'Nyhedsbreve',
		'news_title' => 'Nyheder',
		'approve_title' => 'Godkendelser',
	),
	'de' => Array (
		'title' => 'Erweiterungen',
		'modules' => 'Verfügbare Erweiterungen',
		'shop_title' => 'Shop',
		'board_title' => 'Forum',
		'fe_users_title' => 'Website Benutzer Administration',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Newsletters',
		'news_title' => 'News',
		'approve_title' => 'Zustimmung',
	),
	'no' => Array (
		'title' => 'Plugins',
		'modules' => 'Tilgjengelige plugins',
		'shop_title' => 'Butikk (webshop)',
		'board_title' => 'Forum',
		'fe_users_title' => 'Webområde brukeradministrasjon',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Nyhetsbrev',
		'news_title' => 'Nyheter',
		'approve_title' => 'Godkjennelser',
	),
	'it' => Array (
		'title' => 'Plugins',
		'modules' => 'Plugins disponibili',
		'shop_title' => 'Negozio',
		'board_title' => 'Bacheca messaggi',
		'fe_users_title' => 'Amministrazione utenti web',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Newsletters',
		'news_title' => 'News',
		'approve_title' => 'Approvals',
	),
	'fr' => Array (
		'title' => 'Plugins',
		'modules' => 'Plugins disponibles',
		'shop_title' => 'Magasin',
		'board_title' => 'Forum',
		'fe_users_title' => 'Administration des utilisateurs du site web',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Newsletters',
		'news_title' => 'Nouvelles',
		'approve_title' => 'Acceptation',
	),
	'es' => Array (
		'title' => 'Plugins',
		'modules' => 'Plugins disponibles',
		'shop_title' => 'Tienda',
		'board_title' => 'Tablero de mensajes',
		'fe_users_title' => 'Administración de usuarios del website',
		'dmail_title' => 'Correo Directo',
		'dmail_newsletters' => 'Periódicos',
		'news_title' => 'Noticias',
		'approve_title' => 'Aprovaciones',
	),
	'nl' => Array (
		'title' => 'Plugins',
		'modules' => 'Beschikbare plugins',
		'shop_title' => 'Winkel',
		'board_title' => 'Forum',
		'fe_users_title' => 'Websitegebruikersbeheer',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Nieuwsbrieven',
		'news_title' => 'Nieuws',
		'approve_title' => 'Akkoord',
	),
	'cz' => Array (
		'title' => 'Pluginy',
		'modules' => 'Dostupné pluginy',
		'shop_title' => 'Obchod',
		'board_title' => 'Nástìnka',
		'fe_users_title' => 'Administrace uživatelù website',
		'dmail_title' => 'Direct mail',
		'dmail_newsletters' => 'Bulletiny',
		'news_title' => 'Novinky',
		'approve_title' => 'Souhlasy',
	),
	'pl' => Array (
		'title' => 'Wtyczki',
		'modules' => 'Dostêpne wtyczki',
		'shop_title' => 'Sklep',
		'board_title' => 'Forum dyskusyjne',
		'fe_users_title' => 'Administracja u¿ytkownikami serwisu',
		'dmail_title' => 'Mailing bezpo¶redni',
		'dmail_newsletters' => 'Biuletyny informacyjne',
		'news_title' => 'Newsy',
		'approve_title' => 'Potwierdzenia',
	),
	'si' => Array (
		'shop_title' => 'Trgovina',
		'board_title' => 'Oglasna deska',
		'fe_users_title' => 'Urejanje uporabnikov spletnih strani',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Okrožnice',
		'news_title' => 'Novice',
		'approve_title' => 'Odobritve',
	),
	'fi' => Array (
		'title' => 'Pluginit',
		'modules' => 'Käytettävät pluginit',
		'shop_title' => 'Kauppa',
		'board_title' => 'Keskustelu',
		'fe_users_title' => 'Sivuston hallinnoinnin käyttäjät',
		'dmail_title' => 'Suora sähköposti',
		'dmail_newsletters' => 'Uutislehti',
		'news_title' => 'Uutiset',
		'approve_title' => 'Hyväksyntä',
	),
	'tr' => Array (
		'title' => 'Modüller',
		'modules' => 'Mevcut modüller',
		'shop_title' => 'Maðaza',
		'board_title' => 'Mesaj tahtasý',
		'fe_users_title' => 'Website kullanýcý yönetimi',
		'dmail_title' => 'Doðrudan Mail',
		'dmail_newsletters' => 'Haber mektuplarý',
		'news_title' => 'Haberler',
		'approve_title' => 'Onaylamalar',
	),
	'se' => Array (
	),
	'pt' => Array (
		'title' => 'Plugins',
		'modules' => 'Plugins disponíveis',
		'shop_title' => 'Loja',
		'board_title' => 'Forum',
		'fe_users_title' => 'Administração de utlizadores do site',
		'dmail_title' => 'Direct Mail',
		'dmail_newsletters' => 'Boletim',
		'news_title' => 'Notícias',
		'approve_title' => 'Aprovações',
	),
	'ru' => Array (
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
);
?>